# Generated by Django 3.1.1 on 2020-09-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='BrokerName',
            field=models.CharField(max_length=100, verbose_name='Broker'),
        ),
    ]
